"""
Schemas package.
Contains Pydantic data models for API request/response validation.
"""
from .text_schema import LongTextProcessing
from .script_schema import (
    AuthLoginRequest,
    AuthRegisterRequest,
    AuthResponse,
    Character,
    CharacterRole,
    Dialogue,
    DistributionActionRequest,
    DistributionCreateRequest,
    DistributionJob,
    DistributionPlatform,
    DistributionResponse,
    DistributionStatus,
    ExportFormat,
    ExportResponse,
    ProcessingStep,
    ProcessingStatus,
    ProcessingTask,
    Project,
    ProjectCreateRequest,
    ProjectExport,
    ProjectStatus,
    ProjectUpdateRequest,
    Scene,
    SceneHeading,
    Script,
    ScriptCreateRequest,
    ScriptType,
    TaskCreateRequest,
    TaskDetailResponse,
    TaskListItem,
    TaskListResponse,
    TaskPagination,
    TaskUpdateRequest,
    User,
    UserPublic,
)

__all__ = [
    # Text schemas
    "LongTextProcessing",
    # Script schemas
    "AuthLoginRequest",
    "AuthRegisterRequest",
    "AuthResponse",
    "Character",
    "CharacterRole",
    "Dialogue",
    "DistributionActionRequest",
    "DistributionCreateRequest",
    "DistributionJob",
    "DistributionPlatform",
    "DistributionResponse",
    "DistributionStatus",
    "ExportFormat",
    "ExportResponse",
    "Scene",
    "SceneHeading",
    "ProcessingStep",
    "ProcessingStatus",
    "ProcessingTask",
    "Project",
    "ProjectCreateRequest",
    "ProjectExport",
    "ProjectStatus",
    "ProjectUpdateRequest",
    "Script",
    "ScriptCreateRequest",
    "ScriptType",
    "TaskListItem",
    "TaskPagination",
    "TaskListResponse",
    "TaskDetailResponse",
    "TaskCreateRequest",
    "TaskUpdateRequest",
    "User",
    "UserPublic",
]
